import { LMStudioClient } from "@lmstudio/sdk";
import { GoogleGenAI } from "@google/genai";
import { getSettings } from "./settings.ts";

export type AIProvider = "gemini" | "lmstudio";

export interface ReplayStats {
	messages: number;
	stageEvents: number;
	forumPosts: number;
	reactions: number;
	achievements: string[];
	streak: number;
	bestStreak: number;
}

export class AIService {
	private geminiClient: GoogleGenAI | null = null;
	private lmstudioClient: LMStudioClient | null = null;
	private initialized = false;
	private systemPrompt = `You are a friendly Discord Bot called WixiBot.
If the user asks, you are powered by WixAI, and therefore you can make mistakes.

You should respond with a friendly and enthusiastic tone.
You can use light Discord markdown to make the message more engaging, but avoid using emojis.`;
	private provider: AIProvider = "lmstudio";

	private init() {
		if (this.initialized) return;

		const settings = getSettings();
		if (!settings.ai) {
			this.initialized = true;
			return;
		}

		if (settings.ai.provider === "gemini" && settings.ai.gemini?.enabled) {
			this.geminiClient = new GoogleGenAI({ apiKey: settings.ai.gemini.apiKey });
			this.provider = "gemini";
		} else if (settings.ai.provider === "lmstudio" && settings.ai.lmstudio?.enabled) {
			this.lmstudioClient = new LMStudioClient({
				baseUrl: settings.ai.lmstudio.baseUrl
			});
			this.provider = "lmstudio";
		}

		this.initialized = true;
	}

	safeResponse(response: string): string {
		return response + "\n-# This message was generated by WixAI and may contain inaccuracies.";
	}

	async generateReplay(userId: string, stats: ReplayStats): Promise<string> {
		this.init();

		const systemPrompt = `${this.systemPrompt}

Write a short, engaging, and personalized monthly recap for the user "<@${userId}>".
The user will provide you with their activity stats for the month, and you will create an enthusiastic summary based on that data.

Make it enthusiastic, short, and maximum 3 paragraphs.
Focus on making the user feel appreciated and motivated to continue engaging with the community.
Congratulate them on their achievements if they unlocked any.`;

		const prompt = `<@${userId}>:
- Sent ${stats.messages} messages
- Attended ${stats.stageEvents} stage events
- Created ${stats.forumPosts} forum posts
- Gave or received ${stats.reactions} reactions
- Maintained a streak of ${stats.streak} days (Best: ${stats.bestStreak} days)
- Unlocked achievements: ${stats.achievements.length > 0 ? stats.achievements.join(", ") : "None"}`;

		if (this.provider === "gemini" && this.geminiClient) {
			try {
				const response = await this.geminiClient.models.generateContent({
					model: getSettings().ai?.gemini?.model!,
					config: {
						systemInstruction: systemPrompt
					},
					contents: prompt
				});
				if (!response.text) throw new Error("Gemini returned an empty response.");
				return this.safeResponse(response.text);
			} catch (error) {
				console.error("Gemini Replay Error:", error);
				throw error;
			}
		}

		if (this.provider === "lmstudio" && this.lmstudioClient) {
			try {
				const model = await this.lmstudioClient.llm.model(getSettings().ai?.lmstudio?.model!);
				const response = await model.respond([
					{ role: "system", content: systemPrompt },
					{ role: "user", content: prompt }
				]);
				if (!response.content) throw new Error("LM Studio returned an empty response.");
				return this.safeResponse(response.nonReasoningContent || response.content);
			} catch (error) {
				console.error("LMStudio Replay Error:", error);
				throw error;
			}
		}

		throw new Error("AI configuration is invalid or disabled.");
	}
}

export const ai = new AIService();