import type { Message } from "discord.js";

import { client } from "./client.ts";
import { logger } from "./logger.ts";
import { getSettings } from "./settings.ts";
import { join } from "./utils.ts";

export interface AIResponseToolCalls {

};

export interface AITextContentPart {
	type: "text";
	text: string;
};

export interface AIImageContentPart {
	type: "image_url";
	image_url: {
		url: string;
		detail?: "auto" | "low" | "high" | "original";
	};
};

export type AIMessageContentPart = AITextContentPart | AIImageContentPart;
export type AIMessageContent = string | AIMessageContentPart[];

export interface AIMessage {
	role: "system" | "user" | "assistant" | "tool" | "developer";
	content: AIMessageContent;
	tool_calls?: AIResponseToolCalls[];
};

export interface AIResponseChoice {
	index: number;
	message: AIMessage;
	finish_reason: "stop";
	logprobs: null;
};

export interface AIResponse {
	id: string;
	object: "chat.completion";
	created: number;
	model: string;
	choices: AIResponseChoice[];
	usage: {
		prompt_tokens: number;
		completion_tokens: number;
		total_tokens: number;
		prompt_tokens_details: {
			cached_tokens: number;
			audio_tokens: number;
		};
		completion_tokens_details: {
			reasoning_tokens: number;
			audio_tokens: number;
			accepted_prediction_tokens: number;
			rejected_prediction_tokens: number;
		};
	};
	system_fingerprint: null;
};

export class AIService {
	static disclaimer = "This response is generated by WixAI. Always verify the information provided. [Privacy policy](<https://wixonic.fr/privacy>).";

	private baseURL: string;
	private enabled: boolean;
	private queue: Promise<unknown> = Promise.resolve();

	constructor() {
		const settings = getSettings();
		this.enabled = settings.ai?.enabled ?? false;
		this.baseURL = settings.ai?.baseURL ?? "http://127.0.0.1:8888";
	};

	parseConversation(messages: Message[]): AIMessage[] {
		return messages.map((message) => {
			const images = Array.from(message.attachments.values()).filter((attachment) => {
				if (attachment.contentType?.startsWith("image/")) return true;
				if (attachment.name && /\.(png|jpe?g|webp|gif|svg)$/i.test(attachment.name)) return true;
				if (/\.(png|jpe?g|webp|gif|svg)(\?.*)?$/i.test(attachment.url)) return true;
				return false;
			});

			let text = message.content;
			let role: AIMessage["role"] = "user";

			switch (message.author.id) {
				case client.user?.id:
					role = "assistant";
					break;

				default:
					if (message.author.bot) role = "tool";
					else role = "user";
					text = text ? `<@${message.author.id}> (timestamp: ${new Date(message.createdTimestamp).toISOString()}): ${text}` : `<@${message.author.id}> (timestamp: ${new Date(message.createdTimestamp).toISOString()}):`;
					break;
			}

			if (images.length === 0) return {
				role,
				content: text
			};

			const contentParts: AIMessageContentPart[] = [];
			if (text) contentParts.push({
				type: "text",
				text
			});

			for (const image of images) contentParts.push({
				type: "image_url",
				image_url: {
					url: image.url
				}
			});

			return {
				role,
				content: contentParts
			};
		});
	};

	private async baseRequest(path = "/v1/chat/completions", body = {}, method = "POST") {
		if (!this.enabled) throw new Error("AI service is not enabled.");

		const execute = async () => {
			const settings = getSettings();

			const options: RequestInit = {
				method,
				headers: {
					"Content-Type": "application/json",
					"Authorization": `Bearer ${settings.ai?.apiKey ?? "unsloth"}`
				}
			};

			if (method !== "GET") options.body = JSON.stringify(body);

			const response = await fetch(join(this.baseURL, path), options);
			return await response.json();
		};

		const res = this.queue.then(execute, execute);
		this.queue = res.catch(() => { });
		return await res;
	};

	async factCheck(conversation: AIMessage[]): Promise<{ summary: string; report: string }> {
		logger.debug(`Starting fact checking with ${conversation.length} messages...`);

		const response = await this.request_deep_research([{
			role: "system",
			content: `You are a fact-checking deep research assistant. You will be given a conversation. You should fact-check the information. Always mention the users' names using <@user_id> when referring to their claims.`
		}, ...conversation]);
		const summary = await this.request_summary([{
			role: "system",
			content: `You are a fact-checking summary assistant. You will be given the users' conversation and a fact-check report. Answer in one or few small and concise paragraphs in the users' language. If the report is inconclusive, say so. Always mention the users' names using <@user_id>.`
		}, ...conversation, {
			role: "tool",
			content: `Deep Search Agent: I generated a report based on the user's input and my research:\n\n${response}`
		}]);

		return { summary, report: response };
	};

	private async request_summary(conversation: AIMessage[]): Promise<string> {
		const settings = getSettings();

		logger.debug("Triggering summary run");
		const response = await this.request(conversation, [], settings.ai?.models.summary);
		logger.debug("Summary run finished");

		const content = response.choices[0].message.content;
		if (typeof content === "string") return content;
		return content.filter((part): part is AITextContentPart => part.type === "text").map((part) => part.text).join("\n");
	};

	private async request_deep_research(conversation: AIMessage[]): Promise<string> {
		const settings = getSettings();
		const timestamp = Date.now();
		const threadId = `thread_${timestamp}`;
		const model = settings.ai?.models.deep_research ?? settings.ai?.models.default ?? "unsloth/gemma-4-E2B-it-qat-GGUF:UD-Q4_K_XL";

		try {
			await this.baseRequest("/api/chat/threads", {
				id: threadId,
				title: "Deep Research Task",
				modelType: "base",
				modelId: model,
				createdAt: timestamp,
				updatedAt: timestamp
			}, "POST");

			const threadMessages = conversation.map((message, index) => {
				let role: "user" | "assistant" | "system" = "user";
				if (message.role === "system") role = "system";
				else if (message.role === "assistant") role = "assistant";
				else role = "user";

				const id = `msg_${timestamp}_${index}`;
				const parentId = index > 0 ? `msg_${timestamp}_${index - 1}` : null;

				return {
					id,
					threadId,
					parentId,
					role,
					content: message.content,
					createdAt: timestamp + index
				};
			});

			let userMessage = [...threadMessages].reverse().find((message) => message.role === "user");
			if (!userMessage) {
				userMessage = threadMessages[threadMessages.length - 1];
				userMessage.role = "user";
			}

			await this.baseRequest(`/api/chat/threads/${threadId}/messages`, {
				messages: threadMessages,
				pruneMissing: false
			}, "PUT");

			logger.debug("Triggering deep research run");
			const run = await this.baseRequest("/api/chat/research-runs", {
				threadId,
				userMessageId: userMessage.id,
				inferenceRequest: {
					model
				}
			}, "POST");

			const terminalStatuses = ["completed", "failed", "cancelled", "canceled"];
			let currentRun = run;

			while (!terminalStatuses.includes(currentRun.status)) {
				await new Promise((resolve) => setTimeout(resolve, 2000));
				currentRun = await this.baseRequest(`/api/chat/research-runs/${run.id}`, {}, "GET");

				if (currentRun.status === "awaiting_approval" && currentRun.planRevision && currentRun.planHash) {
					currentRun = await this.baseRequest(`/api/chat/research-runs/${run.id}/approve`, {
						planRevision: currentRun.planRevision,
						planHash: currentRun.planHash
					}, "POST");
				}
			}

			logger.debug(`Deep research run finished with status ${currentRun.status}`);
			return currentRun.report;
		} catch (error) {
			logger.error(`Deep research failed`, { cause: error });
			throw error;
		} finally {
			await this.baseRequest("/api/chat/threads", { ids: [threadId] }, "DELETE").catch(() => { });
		}
	};

	private async request(conversation: AIMessage[], tools: string[] = [], model?: string): Promise<AIResponse> {
		const settings = getSettings();

		return await this.baseRequest("/v1/chat/completions", {
			model: model ?? settings.ai?.models.default ?? "unsloth/gemma-4-E2B-it-qat-GGUF:UD-Q4_K_XL",
			messages: conversation,
			enable_tools: true,
			enabled_tools: ["web_search", ...tools],
			bypass_permissions: true
		});
	};
};