const { ChannelType } = require("discord.js");

const { wait } = require("../utils.js");

/**
 * @type {ListenerInfo}
 */
const listener = {
	name: "Message Create",
	event: "messageCreate",

	/**
	 * @param {import("discord.js").Message} message
	 */
	run: async (bot, logger, message) => {
		if (!message.author.bot) {
			logger.debug(`Message "${message.id}" sent by user "${message.author.username}" (${message.author.id})` + (message.inGuild() ? `, in guild "${message.guild.name}" (${message.guild.id}), in channel "${message.channel.name}" (${message.channel.id})` : ", outside of a guild"));

			if (!message.inGuild() && message.channel.type == ChannelType.DM) {
				const channelId = message.channelId;
				await message.channel.sendTyping()
				const typingInterval = setInterval(() => message.channel.sendTyping(), 5000);

				const fetchedMessages = await message.channel.messages.fetch({
					limit: 20
				});

				const previousMessages = fetchedMessages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);
				previousMessages.delete(fetchedMessages.lastKey());

				/**
				 * @type {import("ollama").Message[]}
				 */
				let messages = [];
				for (const message of previousMessages.values()) {
					if (message.content.startsWith("<｜Clear｜>")) messages = [];
					else {
						if (messages.length == 0) {
							messages.push({
								content: `You are an assistant who's role is to talk casually with people. When responding, keep this in mind:\n-Your name is Wixi, but say I instead.\n- The user's name is ${message.author.username}.\n- Today's date is ${new Date().toLocaleDateString({ language: "fr" })}.\n- Make short answers. Here is the conversation:`,
								role: "assistant"
							});
						}

						messages.push({
							content: message.author.bot ? message.content.slice(0, message.content.lastIndexOf("\n\n-# Generated by WixAI")) : message.content,
							role: message.author.bot ? "assistant" : "user"
						});
					}
				}

				console.log(messages);

				const response = await bot.chatHandler.ask([
					...messages,
					{
						content: `The user's message is: ${message.content}\n\n<think>\n`,
						role: "user"
					}
				]);

				clearInterval(typingInterval);

				const channel = await bot.channels.fetch(channelId);

				const chunkSize = 2000;
				for (let x = 0; x < response.length; x += chunkSize) await channel.send({
					content: response.slice(x, x + chunkSize)
				});
			}
		}
	}
};

module.exports = listener;