const { Ollama } = require("ollama");

class ChatHandler {
	/**
	 * @param {Logger} logger
	 * @param {URL} host
	 */
	constructor(logger, host) {
		this.logger = logger;
		this.ollama = new Ollama({
			host
		});
	};

	/**
	 * @param {import("ollama").Message[]} messages
	 * @param {string} username
	 */
	async ask(messages, username) {
		this.logger.debug("Answering request...");

		const response = await this.ollama.chat({
			model: "deepseek-r1:1.5b",
			messages,
			stream: false,
			options: {
				temperature: 0.6
			}
		});

		this.logger.debug(`Request answered in ${Math.floor(response.total_duration / 1e6) / 1e3}s - ${Math.floor(response.eval_count / response.eval_duration * 1e12) / 1e3} token/s`);

		return `${response.message.content.split(`</think>`)[1].trim()}\n\n-# Generated by WixAI in ${Math.floor(response.total_duration / 1e8) / 1e1}s - ${Math.ceil(response.eval_count / response.eval_duration * 1e9)} token/s\n-# Errors may occur in the responses. Verify the information provided as needed.`;
	};
};

module.exports = ChatHandler;